-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- vim.api.nvim_create_autocmd("CursorHold", {
--   pattern = { "*" },
--   callback = function()
--     vim.lsp.buf.hover()
--     -- if not require("cmp").visible() then
--     --   local hover_fixed = function()
--     --     vim.api.nvim_command("set eventignore=CursorHold")
--     --     vim.api.nvim_command('autocmd CursorMoved ++once set eventignore=" " ')
--     --     vim.lsp.buf.hover()
--     --   end
--     --   hover_fixed()
--     -- end
--   end,
-- })
